kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
spec:
  template:
    spec:
      imagePullSecrets:
        - name: calico-regcred

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: calico-kube-controllers
spec:
  template:
    spec:
      imagePullSecrets:
        - name: calico-regcred