apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds-amd64
spec:
  template:
    spec:
      imagePullSecrets:
        - name: flannel-regcred

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds-arm64
spec:
  template:
    spec:
      imagePullSecrets:
        - name: flannel-regcred

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds-arm
spec:
  template:
    spec:
      imagePullSecrets:
        - name: flannel-regcred

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds-ppc64le
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds-s390x
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
